Repository voycehq/trans-app, pull requests merged in 2022-03, with the labels that each got.

#11 done setting up staticfiles
  app/__init__.py
  static/profile.png
Labels: backend

#12 created database models with dtos
  .env.example
  .gitignore
  app/__init__.py
  app/dto/__init__.py
  app/dto/customer.py
  app/dto/date.py
  app/dto/language.py
  app/dto/language_setting.py
  app/dto/text.py
  app/dto/translated_text.py
  app/dto/workspace.py
  app/dto/workspace_detail.py
  app/dto/workspace_role.py
  app/models/__init__.py
  app/models/customer.py
  app/models/date.py
  app/models/language.py
  app/models/language_setting.py
  app/models/text.py
  app/models/translated_text.py
  app/models/workspace.py
  app/models/workspace_detail.py
  app/models/workspace_role.py
  app/utils/__init__.py
  app/utils/connection.py
  app/utils/session.py
  config.py
Labels: backend

#14 done adding migrations to project
  .gitignore
  README.md
  alembic.example.ini
  migrations/README
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/e93a787ad4ca_project_setup.py
Labels: backend

#15 added dates model
  app/dto/model/__init__.py
  app/dto/model/customer.py
  app/dto/model/date.py
  app/dto/model/language.py
  app/dto/model/language_setting.py
  app/dto/model/text.py
  app/dto/model/translated_text.py
  app/dto/model/workspace.py
  app/dto/model/workspace_detail.py
  app/dto/model/workspace_role.py
  app/models/customer.py
  app/models/date.py
  app/service/__init__.py
  app/service/model/__init__.py
  app/service/model/date.py
  app/utils/session.py
Labels: backend

#26 updates
  alembic.example.ini
  app/__init__.py
Labels: research

#37 workspace creation endpoint
  app/__init__.py
  app/config/authorization.py
  app/controller/auth/email_verification.py
  app/controller/workspace/__init__.py
  app/controller/workspace/workspace.py
  app/dto/controller/workspace.py
  app/dto/model/workspace.py
  app/models/workspace.py
  app/models/workspace_detail.py
  app/service/model/language.py
  app/service/model/workspace.py
  app/service/model/workspace_detail.py
  app/service/model/workspace_role.py
  migrations/versions/9ff2a7b0e42a_.py
  migrations/versions/f638446bf66d_init.py
Labels: backend

#48 added boostrap
  .gitignore
  app/__init__.py
  app/config/bootstrap.py
  app/models/language.py
  app/models/workspace_role.py
  app/service/model/language.py
  app/service/model/workspace_role.py
  migrations/versions/21273e98c7bf_.py
  migrations/versions/4e97867c6cb9_.py
Labels: backend

#52 Get user workspace
  app/__init__.py
  app/controller/workspace/get_workspace.py
  app/dto/model/workspace.py
Labels: backend, work

#55 Done with script for generating audio files for reviewed translated scripts
  .env.example
  app/config/bootstrap.py
  app/dto/model/language_setting.py
  app/dto/model/translated_text.py
  app/engineering/audio_generator.py
  app/models/language_setting.py
  app/models/translated_text.py
  app/service/model/language_setting.py
  app/service/model/translated_text.py
  config.py
Labels: backend

#56 udpates
  .env.example
  .gitignore
  app/config/bootstrap.py
  config.py
Labels: backend

#57 updated dtos
  app/dto/model/text.py
  app/dto/model/translated_text.py
  app/dto/model/workspace_detail.py
Labels: bug, backend

#58 get audio server links
  app/engineering/audio_generator.py
Labels: backend

#59 bootstrap language settings
  app/config/bootstrap.py
  app/models/language_setting.py
  app/service/model/language_setting.py
Labels: backend
